api_platform:
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
  title: Hello API Platform
  version: 1.0.0
  formats:
    jsonld: ["application/ld+json"]
    json: ["application/json"]
  docs_formats:
    jsonld: ["application/ld+json"]
    jsonopenapi: ["application/vnd.openapi+json"]
    html: ["text/html"]
  mapping:
    paths:
      - "%kernel.project_dir%/src/Entity"
  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
    extra_properties:
      standard_put: true
      rfc_7807_compliant_errors: true
  cors:
    allow_origin: ['https://woofwalksfront-prod-production.up.railway.app']
    allow_credentials: true
    allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
    expose_headers: ['Link', 'Content-Type']
    allow_methods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS']
    max_age: 3600

  use_symfony_listeners: true
