nelmio_security:
  #Désactivation pour le dev
  csp:
    enabled: false 
  clickjacking:
    paths:
      '^/': { header: DENY }
  content_type:
    nosniff: true
    #Forçage du HTTPS
  forced_ssl:
    hosts: ['localhost']
    hsts_max_age: 31536000
    hsts_subdomains: true
    hsts_preload: true
