# nelmio_cors:
#   defaults:
#     allow_origin: ["https://localhost:3000"]
#     allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
#     allow_headers: ['Content-Type', 'Authorization']
#     expose_headers: ["Link"]
#     max_age: 3600
#     allow_credentials: true
#   paths:
#     "^/api/":
#       allow_origin: ["https://localhost:3000"]
#       allow_methods: ["GET", "POST", "OPTIONS", "PUT", "PATCH", "DELETE"]
#       allow_headers: ["Content-Type", "Authorization"]
#       max_age: 3600
#       allow_credentials: true
nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true 
    paths:
        '^/': null

# testprod

# nelmio_cors:
#   defaults:
#     allow_origin: ["https://localhost:8443"]
#     allow_methods: ["GET", "POST", "OPTIONS", "PUT", "PATCH", "DELETE"]
#     allow_headers: ["Content-Type", "Authorization"]
#     expose_headers: ["Link"]
#     max_age: 3600
#     allow_credentials: true
#   paths:
#     "^/api/":
#       allow_origin: ["https://localhost:8443"]
#       allow_methods: ["GET", "POST", "OPTIONS", "PUT", "PATCH", "DELETE"]
#       allow_headers: ["Content-Type", "Authorization"]
#       max_age: 3600
#       allow_credentials: true
