# nelmio_cors:
#   defaults:
#     allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#     allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
#     allow_headers: ['Content-Type', 'Authorization', 'X-CSRF-Token', 'x-xsrf-token']
#     expose_headers: ["Link"]
#     max_age: 3600
#     allow_credentials: true
#   paths:
#     "^/api/":
#       allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#       allow_methods: ["GET", "POST", "OPTIONS", "PUT", "PATCH", "DELETE"]
#       allow_headers: ['Content-Type', 'Authorization', 'X-CSRF-Token', 'x-xsrf-token']      
#       max_age: 3600
#       allow_credentials: true

# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_origin: ['https://woofwalksfront-prod-production.up.railway.app']
        allow_credentials: true
        allow_headers: ['Content-Type', 'X-CSRF-Token', 'Authorization']
        allow_methods: ['POST', 'OPTIONS']
        expose_headers: ['XSRF-TOKEN']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['https://woofwalksfront-prod-production.up.railway.app']
            allow_credentials: true
            allow_headers: ['Content-Type', 'X-CSRF-Token', 'Authorization']
            allow_methods: ['POST', 'OPTIONS']


#RAILWAY
# nelmio_cors:
#     defaults:
#         allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#         allow_credentials: true
#         allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
#         expose_headers: ['Link', 'Content-Type']
#         allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
#         max_age: 3600
#     paths:
#         '^/': ~

# testprod
# nelmio_cors:
#   defaults:
#     allow_origin: ["https://localhost:8443"]
#     allow_methods: ["GET", "POST", "OPTIONS", "PUT", "PATCH", "DELETE"]
#     allow_headers: ["Content-Type", "Authorization"]
#     expose_headers: ["Link"]
#     max_age: 3600
#     allow_credentials: true
#   paths:
#     "^/api/":
#       allow_origin: ["https://localhost:8443"]
#       allow_methods: ["GET", "POST", "OPTIONS", "PUT", "PATCH", "DELETE"]
#       allow_headers: ["Content-Type", "Authorization"]
#       max_age: 3600
#       allow_credentials: true
