# nelmio_cors:
#   defaults:
#     allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#     allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
#     allow_headers: ['Content-Type', 'Authorization', 'X-CSRF-Token', 'x-xsrf-token']
#     expose_headers: ["Link"]
#     max_age: 3600
#     allow_credentials: true
#   paths:
#     "^/api/":
#       allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#       allow_methods: ["GET", "POST", "OPTIONS", "PUT", "PATCH", "DELETE"]
#       allow_headers: ['Content-Type', 'Authorization', 'X-CSRF-Token', 'x-xsrf-token']      
#       max_age: 3600
#       allow_credentials: true


nelmio_cors:
  defaults:
    allow_origin: ['https://woofwalksfront-prod-production.up.railway.app']
    allow_credentials: true
    allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
    allow_headers: 
      - 'Content-Type'
      - 'Authorization'
      - 'X-Requested-With'
      - 'X-CSRF-Token'
      - 'Accept'
    expose_headers: 
      - 'Link'
      - 'Content-Type'
    max_age: 3600
  paths:
    "^/api/":
      allow_origin: ['https://woofwalksfront-prod-production.up.railway.app']
      allow_credentials: true
      allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
      allow_headers: 
        - 'Content-Type'
        - 'Authorization'
        - 'X-Requested-With'
        - 'X-CSRF-Token'
        - 'Accept'
      expose_headers: 
        - 'Link'
        - 'Content-Type'
      max_age: 3600
# testprod
# nelmio_cors:
#   defaults:
#     allow_origin: ["https://localhost:8443"]
#     allow_methods: ["GET", "POST", "OPTIONS", "PUT", "PATCH", "DELETE"]
#     allow_headers: ["Content-Type", "Authorization"]
#     expose_headers: ["Link"]
#     max_age: 3600
#     allow_credentials: true
#   paths:
#     "^/api/":
#       allow_origin: ["https://localhost:8443"]
#       allow_methods: ["GET", "POST", "OPTIONS", "PUT", "PATCH", "DELETE"]
#       allow_headers: ["Content-Type", "Authorization"]
#       max_age: 3600
#       allow_credentials: true
