vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    media_object:
      uri_prefix: /media
      upload_destination: "%kernel.project_dir%/public/media"
      # Renommage des fichiers téléchargés avec un suffixe unique.
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
